import localFont from 'next/font/local';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import './globals.css';
import theme from './theme.js';
import { Container } from '@mui/material';
import Navbar from "@/app/components/Header/Navbar";
import Footer from './components/Footer/Footer';

const montserrat = localFont({
  src: './fonts/Montserrat-VariableFont_wght.ttf',
  variable: '--font-geist-sans',
  weight: '100 900',
});
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${montserrat.variable} antialiased`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <Navbar />
          {/* <Container maxWidth="lg" disableGutters> */}
            {children}
            <Footer />
            {/* </Container> */}
            </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
